### PR TITLE
change milvus config format

### PR DESCRIPTION
**Pull request by zc277584121**
hello there, milvus recommends a config format like URI/TOKEN, because in this format, it can flexibly support both milvus-lite/milvus docker/zilliz cloud

here is an docuement example
https://milvus.io/docs/build-rag-with-milvus.md#Load-data-into-Milvus

image

### CODE REVIEW

**Comment by tomsmoker** [comment]
Thanks @zc277584121! I'm just working on a refactor to extract dependencies (see PR here: https://github.com/whyhow-ai/knowledge-table/pull/17) so I'll bring it in once that's done.

**Comment by zc277584121** [comment]
that's great, thank you

**Comment by tomsmoker** [comment]
@zc277584121 merged in the refactor, can you update?

**Comment by zc277584121** [comment]
@tomsmoker I update this PR by merging origin main branch.  The uri/token pattern looks good to me.  But maybe the default name of `vector_db_provider` can be `milvus`, which represent for all of `milvus-lite/milvus docker serive/zilliz cloud`. I think maybe in the code side, we need not to differentiate them. Users can pass in any kind of milvus settings by themselves.  So I updated them in this PR.
This is just a small suggestion. If you have any inconsistent opinions from your business perspective, you can also discard this PR or get further discussion.

**Review by tomsmoker — APPROVED** [review]
I've updated this to reflect the refactor.

**Pull request merged**
